name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: envs
    steps:
      - name: Echo env (debug)
        run: |
          echo "DOCKERHUB_USERNAME is set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "DOCKERHUB_PASSWORD is set: ${{ secrets.DOCKERHUB_PASSWORD != '' }}"
          echo "GITHUB_TOKEN is set: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "TIMESTAMP will be: $(date +%s)"

      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/py-tgbot-4zenen:${{ env.TIMESTAMP }}
            ${{ secrets.DOCKERHUB_USERNAME }}/py-tgbot-4zenen:latest
